version: '3.4'

services:

  pixelart-creator:
    image: ${DOCKER_REGISTRY-}pixelart-creator
    build:
      context: .
      dockerfile: ../../src/PixelartCreator.Presentation/Dockerfile
    ports:
      - 80:80

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: 'P$$ssw0rd' #idk why, but there should be two $ instead of 1
      ACCEPT_EULA: 'Y'
    ports:
      - 1433:1433
    #volumes:
    #  - sql-data:/var/opt/mssql/data

volumes:
  sql-data: