// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PixelartCreator.Infrastructure;

namespace PixelartCreator.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210412182005_SeedBlocksAndColorNames")]
    partial class SeedBlocksAndColorNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PixelartCreator.Domain.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("A")
                        .HasColumnType("tinyint");

                    b.Property<byte>("B")
                        .HasColumnType("tinyint");

                    b.Property<byte>("G")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("R")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            A = (byte)255,
                            B = (byte)56,
                            G = (byte)178,
                            Name = "GRASS",
                            R = (byte)127
                        },
                        new
                        {
                            Id = 3,
                            A = (byte)255,
                            B = (byte)163,
                            G = (byte)233,
                            Name = "SAND",
                            R = (byte)247
                        },
                        new
                        {
                            Id = 4,
                            A = (byte)255,
                            B = (byte)199,
                            G = (byte)199,
                            Name = "WOOL",
                            R = (byte)199
                        },
                        new
                        {
                            Id = 5,
                            A = (byte)255,
                            B = (byte)0,
                            G = (byte)0,
                            Name = "FIRE",
                            R = (byte)255
                        },
                        new
                        {
                            Id = 6,
                            A = (byte)255,
                            B = (byte)255,
                            G = (byte)160,
                            Name = "ICE",
                            R = (byte)160
                        },
                        new
                        {
                            Id = 7,
                            A = (byte)255,
                            B = (byte)167,
                            G = (byte)167,
                            Name = "METAL",
                            R = (byte)167
                        },
                        new
                        {
                            Id = 8,
                            A = (byte)255,
                            B = (byte)0,
                            G = (byte)124,
                            Name = "PLANT",
                            R = (byte)0
                        },
                        new
                        {
                            Id = 9,
                            A = (byte)255,
                            B = (byte)255,
                            G = (byte)255,
                            Name = "SNOW",
                            R = (byte)255
                        },
                        new
                        {
                            Id = 10,
                            A = (byte)255,
                            B = (byte)184,
                            G = (byte)168,
                            Name = "CLAY",
                            R = (byte)164
                        },
                        new
                        {
                            Id = 11,
                            A = (byte)255,
                            B = (byte)77,
                            G = (byte)109,
                            Name = "DIRT",
                            R = (byte)151
                        },
                        new
                        {
                            Id = 12,
                            A = (byte)255,
                            B = (byte)112,
                            G = (byte)112,
                            Name = "STONE",
                            R = (byte)112
                        },
                        new
                        {
                            Id = 13,
                            A = (byte)255,
                            B = (byte)255,
                            G = (byte)64,
                            Name = "WATER",
                            R = (byte)64
                        },
                        new
                        {
                            Id = 14,
                            A = (byte)255,
                            B = (byte)72,
                            G = (byte)119,
                            Name = "WOOD",
                            R = (byte)143
                        },
                        new
                        {
                            Id = 15,
                            A = (byte)255,
                            B = (byte)245,
                            G = (byte)252,
                            Name = "QUARTZ",
                            R = (byte)255
                        },
                        new
                        {
                            Id = 16,
                            A = (byte)255,
                            B = (byte)51,
                            G = (byte)127,
                            Name = "COLOR_ORANGE",
                            R = (byte)216
                        },
                        new
                        {
                            Id = 17,
                            A = (byte)255,
                            B = (byte)216,
                            G = (byte)76,
                            Name = "COLOR_MAGENTA",
                            R = (byte)178
                        },
                        new
                        {
                            Id = 18,
                            A = (byte)255,
                            B = (byte)216,
                            G = (byte)153,
                            Name = "COLOR_LIGHT_BLUE",
                            R = (byte)102
                        },
                        new
                        {
                            Id = 19,
                            A = (byte)255,
                            B = (byte)51,
                            G = (byte)229,
                            Name = "COLOR_YELLOW",
                            R = (byte)229
                        },
                        new
                        {
                            Id = 20,
                            A = (byte)255,
                            B = (byte)25,
                            G = (byte)204,
                            Name = "COLOR_LIGHT_GREEN",
                            R = (byte)127
                        },
                        new
                        {
                            Id = 21,
                            A = (byte)255,
                            B = (byte)165,
                            G = (byte)127,
                            Name = "COLOR_PINK",
                            R = (byte)242
                        },
                        new
                        {
                            Id = 22,
                            A = (byte)255,
                            B = (byte)76,
                            G = (byte)76,
                            Name = "COLOR_GRAY",
                            R = (byte)76
                        },
                        new
                        {
                            Id = 23,
                            A = (byte)255,
                            B = (byte)153,
                            G = (byte)153,
                            Name = "COLOR_LIGHT_GRAY",
                            R = (byte)153
                        },
                        new
                        {
                            Id = 24,
                            A = (byte)255,
                            B = (byte)153,
                            G = (byte)127,
                            Name = "COLOR_CYAN",
                            R = (byte)76
                        },
                        new
                        {
                            Id = 25,
                            A = (byte)255,
                            B = (byte)178,
                            G = (byte)63,
                            Name = "COLOR_PURPLE",
                            R = (byte)127
                        },
                        new
                        {
                            Id = 26,
                            A = (byte)255,
                            B = (byte)178,
                            G = (byte)76,
                            Name = "COLOR_BLUE",
                            R = (byte)51
                        },
                        new
                        {
                            Id = 27,
                            A = (byte)255,
                            B = (byte)51,
                            G = (byte)76,
                            Name = "COLOR_BROWN",
                            R = (byte)102
                        },
                        new
                        {
                            Id = 28,
                            A = (byte)255,
                            B = (byte)51,
                            G = (byte)127,
                            Name = "COLOR_GREEN",
                            R = (byte)102
                        },
                        new
                        {
                            Id = 29,
                            A = (byte)255,
                            B = (byte)51,
                            G = (byte)51,
                            Name = "COLOR_RED",
                            R = (byte)153
                        },
                        new
                        {
                            Id = 30,
                            A = (byte)255,
                            B = (byte)25,
                            G = (byte)25,
                            Name = "COLOR_BLACK",
                            R = (byte)25
                        },
                        new
                        {
                            Id = 31,
                            A = (byte)255,
                            B = (byte)77,
                            G = (byte)238,
                            Name = "GOLD",
                            R = (byte)250
                        },
                        new
                        {
                            Id = 32,
                            A = (byte)255,
                            B = (byte)213,
                            G = (byte)219,
                            Name = "DIAMOND",
                            R = (byte)92
                        },
                        new
                        {
                            Id = 33,
                            A = (byte)255,
                            B = (byte)255,
                            G = (byte)128,
                            Name = "LAPIS",
                            R = (byte)74
                        },
                        new
                        {
                            Id = 34,
                            A = (byte)255,
                            B = (byte)58,
                            G = (byte)217,
                            Name = "EMERALD",
                            R = (byte)0
                        },
                        new
                        {
                            Id = 35,
                            A = (byte)255,
                            B = (byte)49,
                            G = (byte)86,
                            Name = "PODZOL",
                            R = (byte)129
                        },
                        new
                        {
                            Id = 36,
                            A = (byte)255,
                            B = (byte)0,
                            G = (byte)2,
                            Name = "NETHER",
                            R = (byte)112
                        },
                        new
                        {
                            Id = 37,
                            A = (byte)255,
                            B = (byte)161,
                            G = (byte)177,
                            Name = "TERRACOTTA_WHITE",
                            R = (byte)209
                        },
                        new
                        {
                            Id = 38,
                            A = (byte)255,
                            B = (byte)36,
                            G = (byte)82,
                            Name = "TERRACOTTA_ORANGE",
                            R = (byte)159
                        },
                        new
                        {
                            Id = 39,
                            A = (byte)255,
                            B = (byte)108,
                            G = (byte)87,
                            Name = "TERRACOTTA_MAGENTA",
                            R = (byte)149
                        },
                        new
                        {
                            Id = 40,
                            A = (byte)255,
                            B = (byte)138,
                            G = (byte)108,
                            Name = "TERRACOTTA_LIGHT_BLUE",
                            R = (byte)112
                        },
                        new
                        {
                            Id = 41,
                            A = (byte)255,
                            B = (byte)36,
                            G = (byte)133,
                            Name = "TERRACOTTA_YELLOW",
                            R = (byte)186
                        },
                        new
                        {
                            Id = 42,
                            A = (byte)255,
                            B = (byte)53,
                            G = (byte)117,
                            Name = "TERRACOTTA_LIGHT_GREEN",
                            R = (byte)103
                        },
                        new
                        {
                            Id = 43,
                            A = (byte)255,
                            B = (byte)78,
                            G = (byte)77,
                            Name = "TERRACOTTA_PINK",
                            R = (byte)160
                        },
                        new
                        {
                            Id = 44,
                            A = (byte)255,
                            B = (byte)35,
                            G = (byte)41,
                            Name = "TERRACOTTA_GRAY",
                            R = (byte)57
                        },
                        new
                        {
                            Id = 45,
                            A = (byte)255,
                            B = (byte)98,
                            G = (byte)107,
                            Name = "TERRACOTTA_LIGHT_GRAY",
                            R = (byte)135
                        },
                        new
                        {
                            Id = 46,
                            A = (byte)255,
                            B = (byte)92,
                            G = (byte)92,
                            Name = "TERRACOTTA_CYAN",
                            R = (byte)87
                        },
                        new
                        {
                            Id = 47,
                            A = (byte)255,
                            B = (byte)88,
                            G = (byte)73,
                            Name = "TERRACOTTA_PURPLE",
                            R = (byte)122
                        },
                        new
                        {
                            Id = 48,
                            A = (byte)255,
                            B = (byte)92,
                            G = (byte)62,
                            Name = "TERRACOTTA_BLUE",
                            R = (byte)76
                        },
                        new
                        {
                            Id = 49,
                            A = (byte)255,
                            B = (byte)35,
                            G = (byte)50,
                            Name = "TERRACOTTA_BROWN",
                            R = (byte)76
                        },
                        new
                        {
                            Id = 50,
                            A = (byte)255,
                            B = (byte)42,
                            G = (byte)82,
                            Name = "TERRACOTTA_GREEN",
                            R = (byte)76
                        },
                        new
                        {
                            Id = 51,
                            A = (byte)255,
                            B = (byte)46,
                            G = (byte)60,
                            Name = "TERRACOTTA_RED",
                            R = (byte)142
                        },
                        new
                        {
                            Id = 52,
                            A = (byte)255,
                            B = (byte)16,
                            G = (byte)22,
                            Name = "TERRACOTTA_BLACK",
                            R = (byte)37
                        },
                        new
                        {
                            Id = 53,
                            A = (byte)255,
                            B = (byte)49,
                            G = (byte)48,
                            Name = "CRIMSON_NYLIUM",
                            R = (byte)189
                        },
                        new
                        {
                            Id = 54,
                            A = (byte)255,
                            B = (byte)97,
                            G = (byte)63,
                            Name = "CRIMSON_STEM",
                            R = (byte)148
                        },
                        new
                        {
                            Id = 55,
                            A = (byte)255,
                            B = (byte)29,
                            G = (byte)25,
                            Name = "CRIMSON_HYPHAE",
                            R = (byte)92
                        },
                        new
                        {
                            Id = 56,
                            A = (byte)255,
                            B = (byte)134,
                            G = (byte)126,
                            Name = "WARPED_NYLIUM",
                            R = (byte)22
                        },
                        new
                        {
                            Id = 57,
                            A = (byte)255,
                            B = (byte)140,
                            G = (byte)142,
                            Name = "WARPED_STEM",
                            R = (byte)58
                        },
                        new
                        {
                            Id = 58,
                            A = (byte)255,
                            B = (byte)62,
                            G = (byte)44,
                            Name = "WARPED_HYPHAE",
                            R = (byte)86
                        },
                        new
                        {
                            Id = 59,
                            A = (byte)255,
                            B = (byte)133,
                            G = (byte)180,
                            Name = "WARPED_WART_BLOCK",
                            R = (byte)20
                        });
                });

            modelBuilder.Entity("PixelartCreator.Domain.MinecraftBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TexturePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("MinecraftBlocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 2,
                            Name = "Grass Block, Slime Block"
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 3,
                            Name = "Sand"
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 3,
                            Name = "Birch Planks, Birch Log (vertical), Birch Stripped Log, Birch Wood, Birch Stripped Wood, Birch Sign, Birch Pressure Plate, Birch Trapdoor, Birch Stairs, Birch Slab, Birch Fence Gate, Birch Fence, Birch Door, Sandstone"
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 3,
                            Name = "Sandstone slabs"
                        },
                        new
                        {
                            Id = 5,
                            ColorId = 3,
                            Name = "Sandstone stairs"
                        },
                        new
                        {
                            Id = 6,
                            ColorId = 3,
                            Name = "Sandstone walls, Glowstone, End Stone, End Stone Bricks, End Stone Bricks slab"
                        },
                        new
                        {
                            Id = 7,
                            ColorId = 3,
                            Name = "End Stone Bricks stairs"
                        },
                        new
                        {
                            Id = 8,
                            ColorId = 3,
                            Name = "End Stone Bricks wall, Bone Block, Turtle Egg, Scaffolding"
                        },
                        new
                        {
                            Id = 9,
                            ColorId = 4,
                            Name = "Cobweb, Mushroom Stem, Bed (head)"
                        },
                        new
                        {
                            Id = 10,
                            ColorId = 5,
                            Name = "Lava, TNT, Fire, Redstone Block"
                        },
                        new
                        {
                            Id = 11,
                            ColorId = 6,
                            Name = "Ice, Frosted Ice, Packed Ice, Blue Ice"
                        },
                        new
                        {
                            Id = 12,
                            ColorId = 7,
                            Name = "Block of Iron, Iron Door, Brewing Stand, Heavy Weighted Pressure Plate, Iron Trapdoor, Lantern, Anvil, Grindstone, Soul Fire Lantern, Lodestone"
                        },
                        new
                        {
                            Id = 13,
                            ColorId = 8,
                            Name = "Sapling, Flowers, Wheat, Sugar Cane, Pumpkin Stem, Melon Stem, Lily Pad, Cocoa, Carrots, Potatoes, Beetroots, Sweet Berry Bush, Grass, Fern, Vines, Leaves, Cactus, Bamboo"
                        },
                        new
                        {
                            Id = 14,
                            ColorId = 9,
                            Name = "Snow, Snow Block"
                        },
                        new
                        {
                            Id = 15,
                            ColorId = 9,
                            Name = "White Bed (foot), White Wool, White Stained Glass, White Carpet, White Banner, White Shulker Box, White Glazed Terracotta, White Concrete, White Concrete Powder"
                        },
                        new
                        {
                            Id = 16,
                            ColorId = 10,
                            Name = "Clay, Infested Stone"
                        },
                        new
                        {
                            Id = 17,
                            ColorId = 10,
                            Name = "Infested Cobblestone"
                        },
                        new
                        {
                            Id = 18,
                            ColorId = 10,
                            Name = "Infested Stone Brick"
                        },
                        new
                        {
                            Id = 19,
                            ColorId = 10,
                            Name = "Infested Mossy Stone Brick"
                        },
                        new
                        {
                            Id = 20,
                            ColorId = 10,
                            Name = "Infested Cracked Stone Brick"
                        },
                        new
                        {
                            Id = 21,
                            ColorId = 10,
                            Name = "Infested Chiseled Stone Brick"
                        },
                        new
                        {
                            Id = 22,
                            ColorId = 11,
                            Name = "Dirt, Coarse Dirt, Farmland, Grass Path, Granite, Granite slab"
                        },
                        new
                        {
                            Id = 23,
                            ColorId = 11,
                            Name = "Granite stairs"
                        },
                        new
                        {
                            Id = 24,
                            ColorId = 11,
                            Name = "Granite wall, Polished Granite"
                        },
                        new
                        {
                            Id = 25,
                            ColorId = 11,
                            Name = "Polished Granite slab"
                        },
                        new
                        {
                            Id = 26,
                            ColorId = 11,
                            Name = "Polished Granite stairs"
                        },
                        new
                        {
                            Id = 27,
                            ColorId = 11,
                            Name = "Jungle Planks"
                        },
                        new
                        {
                            Id = 28,
                            ColorId = 11,
                            Name = "Jungle Log (vertical), Jungle Stripped Log, Jungle Wood, Jungle Stripped Wood, Jungle Sign, Jungle Pressure Plate, Jungle Trapdoor, Jungle Stairs, Jungle Slab, Jungle Fence Gate, Jungle Fence, Jungle Door, Jukebox, Brown Mushroom Block"
                        },
                        new
                        {
                            Id = 29,
                            ColorId = 12,
                            Name = "Stone (slab, stairs), Andesite (slab"
                        },
                        new
                        {
                            Id = 30,
                            ColorId = 12,
                            Name = "stairs"
                        },
                        new
                        {
                            Id = 31,
                            ColorId = 12,
                            Name = "wall), Polished Andesite (slab"
                        },
                        new
                        {
                            Id = 32,
                            ColorId = 12,
                            Name = "stairs), Cobblestone (slab"
                        },
                        new
                        {
                            Id = 33,
                            ColorId = 12,
                            Name = "stairs), Bedrock, Gold Ore, Iron Ore, Coal Ore, Lapis Lazuli Ore, Dispenser, Mossy Cobblestone (slab"
                        },
                        new
                        {
                            Id = 34,
                            ColorId = 12,
                            Name = "stairs"
                        },
                        new
                        {
                            Id = 35,
                            ColorId = 12,
                            Name = "wall), Spawner, Diamond Ore, Furnace, Stone Pressure Plate, Redstone Ore, Stone Bricks (all variants"
                        },
                        new
                        {
                            Id = 36,
                            ColorId = 12,
                            Name = "all slabs"
                        },
                        new
                        {
                            Id = 37,
                            ColorId = 12,
                            Name = "all stairs"
                        },
                        new
                        {
                            Id = 38,
                            ColorId = 12,
                            Name = "all walls), Emerald Ore, Ender Chest, Dropper, Smooth Stone (slab"
                        },
                        new
                        {
                            Id = 39,
                            ColorId = 12,
                            Name = "stairs), Observer, Smoker, Blast Furnace, Stonecutter, Sticky Piston, Piston, Piston Head, Gravel"
                        },
                        new
                        {
                            Id = 40,
                            ColorId = 12,
                            Name = "Acacia Log (side), Cauldron, Hopper"
                        },
                        new
                        {
                            Id = 41,
                            ColorId = 13,
                            Name = "Kelp, Seagrass, Water, Bubble Column"
                        },
                        new
                        {
                            Id = 42,
                            ColorId = 14,
                            Name = "Oak (Planks, Log (vertical), Stripped Log, Wood, Stripped Wood, Sign, Door, Pressure Plate, Fence, Trapdoor, Fence Gate, Slab, Stairs), Note Block, Bookshelf, Chest, Crafting Table, Trapped Chest, Daylight Detector, Loom, Barrel, Cartography Table, Fletching Table, Lectern, Smithing Table, Composter, Bamboo Sapling, Dead Bush, Petrified Oak Slab, Beehive"
                        },
                        new
                        {
                            Id = 43,
                            ColorId = 15,
                            Name = "Diorite, Polished Diorite"
                        },
                        new
                        {
                            Id = 44,
                            ColorId = 15,
                            Name = "Birch Log (side), Quartz Block (all variants"
                        },
                        new
                        {
                            Id = 45,
                            ColorId = 15,
                            Name = "all slabs"
                        },
                        new
                        {
                            Id = 46,
                            ColorId = 15,
                            Name = "all stairs), Sea Lantern, Target"
                        },
                        new
                        {
                            Id = 47,
                            ColorId = 16,
                            Name = "Acacia (Planks, Log (vertical), Stripped Log, Stripped Wood, Sign, Trapdoor, Slab), Red Sand"
                        },
                        new
                        {
                            Id = 48,
                            ColorId = 16,
                            Name = "Orange (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Pumpkin, Carved Pumpkin, Jack o'Lantern, Terracotta, Red Sandstone (all variants"
                        },
                        new
                        {
                            Id = 49,
                            ColorId = 16,
                            Name = "all stairs"
                        },
                        new
                        {
                            Id = 50,
                            ColorId = 16,
                            Name = "all slabs"
                        },
                        new
                        {
                            Id = 51,
                            ColorId = 16,
                            Name = "all walls), Honey Block, Honeycomb Block"
                        },
                        new
                        {
                            Id = 52,
                            ColorId = 17,
                            Name = "Magenta (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Purpur (all variants"
                        },
                        new
                        {
                            Id = 53,
                            ColorId = 17,
                            Name = "slab"
                        },
                        new
                        {
                            Id = 54,
                            ColorId = 17,
                            Name = "stairs)"
                        },
                        new
                        {
                            Id = 55,
                            ColorId = 18,
                            Name = "Light Blue (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Soul Fire"
                        },
                        new
                        {
                            Id = 56,
                            ColorId = 19,
                            Name = "Sponge, Wet Sponge"
                        },
                        new
                        {
                            Id = 57,
                            ColorId = 19,
                            Name = "Yellow (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Hay Bale"
                        },
                        new
                        {
                            Id = 58,
                            ColorId = 19,
                            Name = "Horn Coral (Coral Block, Coral, Coral Fan), Bee Nest"
                        },
                        new
                        {
                            Id = 59,
                            ColorId = 20,
                            Name = "Lime (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Melon"
                        },
                        new
                        {
                            Id = 60,
                            ColorId = 21,
                            Name = "Pink (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder)"
                        },
                        new
                        {
                            Id = 61,
                            ColorId = 21,
                            Name = "Brain Coral (Coral Block, Coral, Coral Fan)"
                        },
                        new
                        {
                            Id = 62,
                            ColorId = 22,
                            Name = "Acacia Wood"
                        },
                        new
                        {
                            Id = 63,
                            ColorId = 22,
                            Name = "Gray (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder)"
                        },
                        new
                        {
                            Id = 64,
                            ColorId = 22,
                            Name = "Dead Coral (Coral Block, Coral, Coral Fan)"
                        },
                        new
                        {
                            Id = 65,
                            ColorId = 23,
                            Name = "Light Gray (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Structure Block, Jigsaw Block"
                        },
                        new
                        {
                            Id = 66,
                            ColorId = 24,
                            Name = "Cyan (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Prismarine (slab"
                        },
                        new
                        {
                            Id = 67,
                            ColorId = 24,
                            Name = "stairs"
                        },
                        new
                        {
                            Id = 68,
                            ColorId = 24,
                            Name = "wall)"
                        },
                        new
                        {
                            Id = 69,
                            ColorId = 24,
                            Name = "Warped (Roots, Pressure Plate, Fence, Trapdoor, Fence Gate, Door, Sign, Fungus), Twisting Vines, Nether Sprouts"
                        },
                        new
                        {
                            Id = 70,
                            ColorId = 25,
                            Name = "Shulker Box"
                        },
                        new
                        {
                            Id = 71,
                            ColorId = 25,
                            Name = "Purple (Wool, Carpet, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Mycelium, Chorus Plant, Chorus Flower, Repeating Command Block"
                        },
                        new
                        {
                            Id = 72,
                            ColorId = 25,
                            Name = "Bubble Coral (Coral Block, Coral, Coral Fan)"
                        },
                        new
                        {
                            Id = 73,
                            ColorId = 26,
                            Name = "Blue (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder)"
                        },
                        new
                        {
                            Id = 74,
                            ColorId = 26,
                            Name = "Tube Coral (Coral Block, Coral, Coral Fan)"
                        },
                        new
                        {
                            Id = 75,
                            ColorId = 27,
                            Name = "Dark Oak (Planks, Log, Stripped Log, Wood, Stripped Wood, Sign, Pressure Plate, Trapdoor, Stairs, Slab, Fence Gate, Fence, Door)"
                        },
                        new
                        {
                            Id = 76,
                            ColorId = 27,
                            Name = "Spruce Log (side)"
                        },
                        new
                        {
                            Id = 77,
                            ColorId = 27,
                            Name = "Brown (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Soul Sand, Command Block, Brown Mushroom, Soul Soil"
                        },
                        new
                        {
                            Id = 78,
                            ColorId = 28,
                            Name = "Green (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), End Portal Frame, Chain Command Block, Dried Kelp Block, Sea Pickle"
                        },
                        new
                        {
                            Id = 79,
                            ColorId = 29,
                            Name = "Red (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Bricks (slab"
                        },
                        new
                        {
                            Id = 80,
                            ColorId = 29,
                            Name = "stairs"
                        },
                        new
                        {
                            Id = 81,
                            ColorId = 29,
                            Name = "wall), Red Mushroom Block, Nether Wart, Enchanting Table, Nether Wart Block"
                        },
                        new
                        {
                            Id = 82,
                            ColorId = 29,
                            Name = "Fire Coral (Coral Block, Coral, Coral Fan), Red Mushroom, Shroomlight"
                        },
                        new
                        {
                            Id = 83,
                            ColorId = 30,
                            Name = "Black (Wool, Carpet, Shulker Box, Bed (foot), Stained Glass, Banner, Glazed Terracotta, Concrete, Concrete Powder), Obsidian, End Portal, Dragon Egg, Coal Block, End Gateway, Basalt, Polished Basalt, Block of Netherite, Ancient Debris, Crying Obsidian, Respawn Anchor, Blackstone, Polished Blackstone, Polished Blackstone Bricks, Gilded Blackstone"
                        },
                        new
                        {
                            Id = 84,
                            ColorId = 31,
                            Name = "Block of Gold, Light Weighted Pressure Plate, Bell"
                        },
                        new
                        {
                            Id = 85,
                            ColorId = 32,
                            Name = "Block of Diamond, Beacon, Prismarine Bricks (slab"
                        },
                        new
                        {
                            Id = 86,
                            ColorId = 32,
                            Name = "stairs), Dark Prismarine (slab"
                        },
                        new
                        {
                            Id = 87,
                            ColorId = 32,
                            Name = "stairs), Conduit"
                        },
                        new
                        {
                            Id = 88,
                            ColorId = 33,
                            Name = "Lapis Lazuli Block"
                        },
                        new
                        {
                            Id = 89,
                            ColorId = 34,
                            Name = "Block of Emerald"
                        },
                        new
                        {
                            Id = 90,
                            ColorId = 35,
                            Name = "Podzol"
                        },
                        new
                        {
                            Id = 91,
                            ColorId = 35,
                            Name = "Spruce (Planks, Log (vertical), Stripped Log, Wood, Stripped Wood, Sign, Pressure Plate, Trapdoor, Stairs, Slab, Fence Gate, Fence, Door)"
                        },
                        new
                        {
                            Id = 92,
                            ColorId = 35,
                            Name = "Oak Log (side)"
                        },
                        new
                        {
                            Id = 93,
                            ColorId = 35,
                            Name = "Jungle Log (side), Campfire, Soul Campfire"
                        },
                        new
                        {
                            Id = 94,
                            ColorId = 36,
                            Name = "Netherrack, Nether Bricks (fence"
                        },
                        new
                        {
                            Id = 95,
                            ColorId = 36,
                            Name = "slab"
                        },
                        new
                        {
                            Id = 96,
                            ColorId = 36,
                            Name = "stairs"
                        },
                        new
                        {
                            Id = 97,
                            ColorId = 36,
                            Name = "wall"
                        },
                        new
                        {
                            Id = 98,
                            ColorId = 36,
                            Name = "chiseled"
                        },
                        new
                        {
                            Id = 99,
                            ColorId = 36,
                            Name = "cracked), Nether Gold Ore, Nether Quartz Ore, Magma Block, Red Nether Bricks (slab"
                        },
                        new
                        {
                            Id = 100,
                            ColorId = 36,
                            Name = "stairs"
                        },
                        new
                        {
                            Id = 101,
                            ColorId = 36,
                            Name = "wall)"
                        },
                        new
                        {
                            Id = 102,
                            ColorId = 36,
                            Name = "Crimson (Roots, Pressure Plate, Fence, Trapdoor, Fence Gate, Door, Sign, Fungus), Weeping Vines"
                        },
                        new
                        {
                            Id = 103,
                            ColorId = 37,
                            Name = "White Terracotta"
                        },
                        new
                        {
                            Id = 104,
                            ColorId = 38,
                            Name = "Orange Terracotta"
                        },
                        new
                        {
                            Id = 105,
                            ColorId = 39,
                            Name = "Magenta Terracotta"
                        },
                        new
                        {
                            Id = 106,
                            ColorId = 40,
                            Name = "Light Blue Terracotta"
                        },
                        new
                        {
                            Id = 107,
                            ColorId = 41,
                            Name = "Yellow Terracotta"
                        },
                        new
                        {
                            Id = 108,
                            ColorId = 42,
                            Name = "Lime Terracotta"
                        },
                        new
                        {
                            Id = 109,
                            ColorId = 43,
                            Name = "Pink Terracotta"
                        },
                        new
                        {
                            Id = 110,
                            ColorId = 44,
                            Name = "Gray Terracotta"
                        },
                        new
                        {
                            Id = 111,
                            ColorId = 45,
                            Name = "Light Gray Terracotta"
                        },
                        new
                        {
                            Id = 112,
                            ColorId = 46,
                            Name = "Cyan Terracotta"
                        },
                        new
                        {
                            Id = 113,
                            ColorId = 47,
                            Name = "Purple (Terracotta, Shulker Box)"
                        },
                        new
                        {
                            Id = 114,
                            ColorId = 48,
                            Name = "Blue Terracotta"
                        },
                        new
                        {
                            Id = 115,
                            ColorId = 49,
                            Name = "Brown Terracotta"
                        },
                        new
                        {
                            Id = 116,
                            ColorId = 50,
                            Name = "Green Terracotta"
                        },
                        new
                        {
                            Id = 117,
                            ColorId = 51,
                            Name = "Red Terracotta"
                        },
                        new
                        {
                            Id = 118,
                            ColorId = 52,
                            Name = "Black Terracotta"
                        },
                        new
                        {
                            Id = 119,
                            ColorId = 53,
                            Name = "Crimson Nylium"
                        },
                        new
                        {
                            Id = 120,
                            ColorId = 54,
                            Name = "Crimson (Stem, Stripped Stem, Planks, Stairs, Slab)"
                        },
                        new
                        {
                            Id = 121,
                            ColorId = 55,
                            Name = "Crimson (Hyphae, Stripped Hyphae)"
                        },
                        new
                        {
                            Id = 122,
                            ColorId = 56,
                            Name = "Warped Nylium"
                        },
                        new
                        {
                            Id = 123,
                            ColorId = 57,
                            Name = "Warped (Stem, Stripped Stem, Planks, Stairs, Slab)"
                        },
                        new
                        {
                            Id = 124,
                            ColorId = 58,
                            Name = "Warped (Hyphae, Stripped Hyphae)"
                        },
                        new
                        {
                            Id = 125,
                            ColorId = 59,
                            Name = "Warped Wart Block"
                        });
                });

            modelBuilder.Entity("PixelartCreator.Domain.Pixelart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pixelarts");
                });

            modelBuilder.Entity("PixelartCreator.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("PixelartCreator.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("PixelartCreator.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelartCreator.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("PixelartCreator.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PixelartCreator.Domain.MinecraftBlock", b =>
                {
                    b.HasOne("PixelartCreator.Domain.Color", "MapColor")
                        .WithMany("Blocks")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapColor");
                });

            modelBuilder.Entity("PixelartCreator.Domain.Pixelart", b =>
                {
                    b.HasOne("PixelartCreator.Domain.User", "User")
                        .WithMany("Pixelarts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PixelartCreator.Domain.Color", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("PixelartCreator.Domain.User", b =>
                {
                    b.Navigation("Pixelarts");
                });
#pragma warning restore 612, 618
        }
    }
}
